# Generated by Django 2.2.3 on 2019-07-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20190712_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='worker',
            name='post',
            field=models.CharField(blank=True, choices=[('D', 'Designer'), ('A', 'Analyst'), ('M', 'Manager'), ('T', 'Tester'), ('D', 'Developer'), ('E', 'Engineer'), ('L', 'Lead')], default='E', max_length=1),
        ),
    ]
