# Generated by Django 2.2.3 on 2019-07-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20190712_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='time_of_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='time_of_start',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
