# Generated by Django 2.1.8 on 2019-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_auto_20190713_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
