# Generated by Django 2.1.8 on 2019-07-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0020_auto_20190714_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracker.Worker'),
        ),
    ]
