# Generated by Django 2.1.8 on 2019-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0021_auto_20190714_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Ivan', max_length=50),
            preserve_default=False,
        ),
    ]
