# Generated by Django 2.1.8 on 2019-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0022_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
