# Generated by Django 2.1.8 on 2019-07-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0024_auto_20190714_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_of_start']},
        ),
    ]
