# Generated by Django 2.1.8 on 2019-07-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0025_auto_20190714_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_of_start']},
        ),
    ]
