# Generated by Django 2.1.8 on 2019-07-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0026_auto_20190714_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
