# Generated by Django 2.1.8 on 2019-07-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0029_auto_20190714_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-time_of_start']},
        ),
    ]
