# Generated by Django 2.1.8 on 2019-07-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0030_auto_20190714_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_of_start']},
        ),
    ]
