# Generated by Django 2.1.8 on 2019-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0032_auto_20190714_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
