# Generated by Django 2.1.8 on 2019-07-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0033_auto_20190714_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.CharField(blank=True, default='24:00:00', max_length=10, null=True),
        ),
    ]
