# Generated by Django 2.1.8 on 2019-07-14 19:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0034_auto_20190714_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', tinymce.models.HTMLField(verbose_name='message')),
                ('status', models.CharField(default='new', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tracker.Worker')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
