# Generated by Django 2.1.8 on 2019-07-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0035_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=10, null=True),
        ),
    ]
