# Generated by Django 2.1.8 on 2019-07-14 20:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0037_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=tinymce.models.HTMLField(verbose_name='Message'),
        ),
    ]
