# Generated by Django 2.1.10 on 2019-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0043_auto_20190714_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='spend_time',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
    ]
