# Generated by Django 2.1.10 on 2019-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0044_task_spend_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='is_completed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
