# Generated by Django 2.1.10 on 2019-07-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0045_timelog_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='spend_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
