# Generated by Django 2.1.10 on 2019-07-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0046_auto_20190715_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='spend_time',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
    ]
