# Generated by Django 2.1.10 on 2019-07-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0047_auto_20190715_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_of_start']},
        ),
    ]
