# Generated by Django 2.1.10 on 2019-07-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0049_auto_20190715_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_of_start', 'is_completed']},
        ),
    ]
