# Generated by Django 2.1.10 on 2019-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0050_auto_20190715_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(default='1995-12-12'),
            preserve_default=False,
        ),
    ]
