# Generated by Django 2.1.10 on 2019-07-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0051_auto_20190716_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
