# Generated by Django 2.1.10 on 2019-07-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0053_auto_20190716_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, default='img/default.webp', null=True, upload_to='avatars'),
        ),
    ]
