# Generated by Django 2.1.10 on 2019-07-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0054_auto_20190716_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(help_text='Select a worker for this project', related_name='project_worker', to='Tracker.Worker'),
        ),
    ]
