# Generated by Django 2.1.10 on 2019-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0055_auto_20190717_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
