# Generated by Django 2.1.10 on 2019-07-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0056_project_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on', 'is_completed']},
        ),
    ]
