# Generated by Django 2.1.10 on 2019-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0057_auto_20190717_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_of_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
