# Generated by Django 2.1.10 on 2019-07-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0059_auto_20190717_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_of_task',
            field=models.CharField(blank=True, choices=[('B', 'Bug'), ('F', 'Feature')], default='F', max_length=1),
        ),
    ]
