# Generated by Django 2.1.10 on 2019-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0060_auto_20190717_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='is_single',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
