# Generated by Django 2.1.10 on 2019-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0062_auto_20190718_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
