# Generated by Django 2.1.10 on 2019-07-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0063_auto_20190718_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_available',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
