# Generated by Django 2.1.10 on 2019-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0064_task_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='action',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
