# Generated by Django 2.1.10 on 2019-07-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0070_worker_date_of_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['-date_of_start']},
        ),
    ]
