# Generated by Django 2.1.10 on 2019-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0071_auto_20190721_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='spend_time',
            field=models.CharField(default='00:00:00', max_length=9),
        ),
    ]
