# Generated by Django 2.1.10 on 2019-07-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0072_task_spend_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['-date_of_start', 'is_blocked']},
        ),
    ]
