# Generated by Django 2.1.10 on 2019-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0073_auto_20190721_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='available_from',
            field=models.DateField(default='2019-07-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='available_to',
            field=models.DateField(default='2019-07-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_of_task',
            field=models.CharField(choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'High'), ('I', 'Important'), ('U', 'Urgent')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_of_task',
            field=models.CharField(choices=[('B', 'Bug'), ('F', 'Feature'), ('T', 'Task'), ('T', 'Task'), ('I', 'Improvement')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(default='2019-07-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='post',
            field=models.CharField(choices=[('A', 'Analyst'), ('D', 'Designer'), ('M', 'Manager'), ('T', 'Tester'), ('P', 'Programmer'), ('E', 'Engineer'), ('L', 'Lead')], default='E', max_length=1),
        ),
    ]
